// data.ts

export type User = {
  id: string;
  username: string;
  email: string;
  phone: string;
  location: string;
  status: "pending" | "processing" | "success" | "failed";
  role: "admin" | "user";
};

export const users: User[] = [
  {
    id: "1",
    username: "saaim_ahmed",
    email: "saaim.ahmed@example.com",
    phone: "+8801711000001",
    location: "Dhaka",
    status: "success",
    role: "admin",
  },
  {
    id: "2",
    username: "fardous_h",
    email: "fardous.h@example.com",
    phone: "+8801711000002",
    location: "Chittagong",
    status: "processing",
    role: "user",
  },
  {
    id: "3",
    username: "musfiqur_r",
    email: "musfiqur.r@example.com",
    phone: "+8801711000003",
    location: "Sylhet",
    status: "pending",
    role: "user",
  },
  {
    id: "4",
    username: "arif_khan",
    email: "arif.khan@example.com",
    phone: "+8801711000004",
    location: "Khulna",
    status: "failed",
    role: "admin",
  },
  {
    id: "5",
    username: "nabila_akter",
    email: "nabila.akter@example.com",
    phone: "+8801711000005",
    location: "Rajshahi",
    status: "success",
    role: "user",
  },
  {
    id: "6",
    username: "imran_hossain",
    email: "imran.h@example.com",
    phone: "+8801711000006",
    location: "Barishal",
    status: "pending",
    role: "admin",
  },
  {
    id: "7",
    username: "sumaiya_j",
    email: "sumaiya.j@example.com",
    phone: "+8801711000007",
    location: "Rangpur",
    status: "processing",
    role: "user",
  },
  {
    id: "8",
    username: "tanvir_h",
    email: "tanvir.h@example.com",
    phone: "+8801711000008",
    location: "Mymensingh",
    status: "success",
    role: "user",
  },
  {
    id: "9",
    username: "shakib_hasan",
    email: "shakib.h@example.com",
    phone: "+8801711000009",
    location: "Dhaka",
    status: "failed",
    role: "admin",
  },
  {
    id: "10",
    username: "mim_akter",
    email: "mim.akter@example.com",
    phone: "+8801711000010",
    location: "Chittagong",
    status: "processing",
    role: "user",
  },
  {
    id: "11",
    username: "rafi_k",
    email: "rafi.k@example.com",
    phone: "+8801711000011",
    location: "Sylhet",
    status: "pending",
    role: "user",
  },
  {
    id: "12",
    username: "farzana_r",
    email: "farzana.r@example.com",
    phone: "+8801711000012",
    location: "Rajshahi",
    status: "success",
    role: "user",
  },
  {
    id: "13",
    username: "jubayer_a",
    email: "jubayer.a@example.com",
    phone: "+8801711000013",
    location: "Khulna",
    status: "processing",
    role: "admin",
  },
  {
    id: "14",
    username: "tasnim_akter",
    email: "tasnim.a@example.com",
    phone: "+8801711000014",
    location: "Dhaka",
    status: "failed",
    role: "user",
  },
  {
    id: "15",
    username: "mahmudul_h",
    email: "mahmudul.h@example.com",
    phone: "+8801711000015",
    location: "Barishal",
    status: "success",
    role: "admin",
  },
  {
    id: "16",
    username: "rasel_ahmed",
    email: "rasel.a@example.com",
    phone: "+8801711000016",
    location: "Mymensingh",
    status: "pending",
    role: "user",
  },
  {
    id: "17",
    username: "nusrat_jahan",
    email: "nusrat.j@example.com",
    phone: "+8801711000017",
    location: "Rangpur",
    status: "processing",
    role: "user",
  },
  {
    id: "18",
    username: "hasan_mahmud",
    email: "hasan.m@example.com",
    phone: "+8801711000018",
    location: "Sylhet",
    status: "success",
    role: "admin",
  },
  {
    id: "19",
    username: "tania_akter",
    email: "tania.a@example.com",
    phone: "+8801711000019",
    location: "Dhaka",
    status: "pending",
    role: "user",
  },
  {
    id: "20",
    username: "omar_faruk",
    email: "omar.f@example.com",
    phone: "+8801711000020",
    location: "Rajshahi",
    status: "failed",
    role: "user",
  },
  // --- keep repeating pattern until 50+ users ---
  {
    id: "21",
    username: "zahid_hossain",
    email: "zahid.h@example.com",
    phone: "+8801711000021",
    location: "Chittagong",
    status: "success",
    role: "admin",
  },
  {
    id: "22",
    username: "shahina_akter",
    email: "shahina.a@example.com",
    phone: "+8801711000022",
    location: "Khulna",
    status: "processing",
    role: "user",
  },
  {
    id: "23",
    username: "kamal_hossain",
    email: "kamal.h@example.com",
    phone: "+8801711000023",
    location: "Dhaka",
    status: "pending",
    role: "user",
  },
  {
    id: "24",
    username: "labiba_akter",
    email: "labiba.a@example.com",
    phone: "+8801711000024",
    location: "Barishal",
    status: "failed",
    role: "admin",
  },
  {
    id: "25",
    username: "shihab_ahmed",
    email: "shihab.a@example.com",
    phone: "+8801711000025",
    location: "Rajshahi",
    status: "success",
    role: "user",
  },
  {
    id: "26",
    username: "maisha_akter",
    email: "maisha.a@example.com",
    phone: "+8801711000026",
    location: "Sylhet",
    status: "processing",
    role: "user",
  },
  {
    id: "27",
    username: "robin_khan",
    email: "robin.k@example.com",
    phone: "+8801711000027",
    location: "Mymensingh",
    status: "pending",
    role: "admin",
  },
  {
    id: "28",
    username: "sadia_hossain",
    email: "sadia.h@example.com",
    phone: "+8801711000028",
    location: "Rangpur",
    status: "success",
    role: "user",
  },
  {
    id: "29",
    username: "tamim_iqbal",
    email: "tamim.i@example.com",
    phone: "+8801711000029",
    location: "Dhaka",
    status: "processing",
    role: "user",
  },
  {
    id: "30",
    username: "nayeem_hasan",
    email: "nayeem.h@example.com",
    phone: "+8801711000030",
    location: "Khulna",
    status: "failed",
    role: "admin",
  },
  // ... continue until 50+
]
